title: PikaPods Docs
description: Notes on selected apps and PikaPods controls
baseurl: ""
url: "https://docs.pikapods.com"
logo: favicon.png
favicon_ico: favicon.ico

permalink: /404.html
include: ["_redirects"]
exclude: ["README.md", "Rakefile", "vendor"]

search_enabled: true
heading_anchors: true

aux_links:
  "Start Free with $5 Welcome Credit":
    - "https://www.pikapods.com"

theme: just-the-docs
color_scheme: pikapods
callouts:
  note:
    title: Note
    color: grey-dk
kramdown:
  toc_levels: 1..3

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
